#!/bin/bash

# Switch to Custom Server (Company-hosted PostgreSQL)
# This script updates .env to use a custom PostgreSQL server via PostgREST

cd "$(dirname "$0")/.."

echo "Switching to Custom Server mode..."
echo ""
echo "Please provide the following information:"
echo ""

# Prompt for custom server URL
read -p "Custom Server URL (e.g., http://localhost:3000 or http://company-server:3000): " CUSTOM_URL
if [ -z "$CUSTOM_URL" ]; then
    echo "❌ Custom server URL is required"
    exit 1
fi

# Prompt for API key
read -p "PostgREST API Key (anon key): " CUSTOM_KEY
if [ -z "$CUSTOM_KEY" ]; then
    echo "❌ API key is required"
    exit 1
fi

# Prompt for schema (optional)
read -p "Database schema (default: public): " CUSTOM_SCHEMA
CUSTOM_SCHEMA=${CUSTOM_SCHEMA:-public}

# Create/update .env
cat > .env << EOF
# BetSure Dialer - CUSTOM SERVER
# Auto-generated by use-custom-server.sh

# Database Mode
VITE_DATABASE_MODE=custom-server

# Custom Server Configuration
VITE_CUSTOM_DB_URL=${CUSTOM_URL}
VITE_CUSTOM_DB_KEY=${CUSTOM_KEY}
VITE_CUSTOM_DB_SCHEMA=${CUSTOM_SCHEMA}

# App Configuration
VITE_APP_NAME=BetSure Dialer
VITE_APP_ENV=production

# Feature Flags
VITE_ENABLE_WHATSAPP=true
VITE_ENABLE_AI_COACH=true
VITE_ENABLE_CALL_RECORDING=true
EOF

echo ""
echo "✓ .env updated for Custom Server mode"
echo ""
echo "Custom Server Configuration:"
echo "  - URL: ${CUSTOM_URL}"
echo "  - Schema: ${CUSTOM_SCHEMA}"
echo ""
echo "⚠️  Note: Make sure your PostgREST server is running and accessible"
echo "⚠️  Note: Ensure your database schema matches Supabase structure"
echo ""
echo "Run 'npm run dev' to start the app"

