# Switch to Custom Server (Company-hosted PostgreSQL)
# PowerShell script for Windows users
# This script updates .env to use a custom PostgreSQL server via PostgREST

$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptPath
Set-Location $projectRoot

Write-Host "Switching to Custom Server mode..." -ForegroundColor Cyan
Write-Host ""

# Prompt for custom server URL
$customUrl = Read-Host "Custom Server URL (e.g., http://localhost:3000 or http://company-server:3000)"
if ([string]::IsNullOrWhiteSpace($customUrl)) {
    Write-Host "❌ Custom server URL is required" -ForegroundColor Red
    exit 1
}

# Prompt for API key
$customKey = Read-Host "PostgREST API Key (anon key)"
if ([string]::IsNullOrWhiteSpace($customKey)) {
    Write-Host "❌ API key is required" -ForegroundColor Red
    exit 1
}

# Prompt for schema (optional)
$customSchema = Read-Host "Database schema (default: public)"
if ([string]::IsNullOrWhiteSpace($customSchema)) {
    $customSchema = "public"
}

# Create/update .env
$envContent = @"
# BetSure Dialer - CUSTOM SERVER
# Auto-generated by use-custom-server.ps1

# Database Mode
VITE_DATABASE_MODE=custom-server

# Custom Server Configuration
VITE_CUSTOM_DB_URL=$customUrl
VITE_CUSTOM_DB_KEY=$customKey
VITE_CUSTOM_DB_SCHEMA=$customSchema

# App Configuration
VITE_APP_NAME=BetSure Dialer
VITE_APP_ENV=production

# Feature Flags
VITE_ENABLE_WHATSAPP=true
VITE_ENABLE_AI_COACH=true
VITE_ENABLE_CALL_RECORDING=true
"@

$envContent | Out-File -FilePath ".env" -Encoding utf8 -NoNewline

Write-Host ""
Write-Host "✓ .env updated for Custom Server mode" -ForegroundColor Green
Write-Host ""
Write-Host "Custom Server Configuration:"
Write-Host "  - URL: $customUrl"
Write-Host "  - Schema: $customSchema"
Write-Host ""
Write-Host "⚠️  Note: Make sure your PostgREST server is running and accessible" -ForegroundColor Yellow
Write-Host "⚠️  Note: Ensure your database schema matches Supabase structure" -ForegroundColor Yellow
Write-Host ""
Write-Host "Run 'npm run dev' to start the app"

