#!/bin/bash

# Switch to Local Supabase
# This script updates .env to use local Supabase

cd "$(dirname "$0")/.."

echo "Switching to Local Supabase..."

# Check if Supabase is running
if ! supabase status &> /dev/null; then
    echo "❌ Local Supabase is not running."
    echo "   Start it with: ./scripts/setup-local-supabase.sh"
    exit 1
fi

# Get the anon key from Supabase status
ANON_KEY=$(supabase status | grep "anon key" | awk '{print $NF}')

if [ -z "$ANON_KEY" ]; then
    echo "❌ Could not get anon key. Is Supabase running?"
    exit 1
fi

# Create/update .env.local
cat > .env << EOF
# BetSure Dialer - LOCAL Development
# Auto-generated by use-local-supabase.sh

# Local Supabase
VITE_SUPABASE_URL=http://127.0.0.1:54321
VITE_SUPABASE_ANON_KEY=${ANON_KEY}

# App Configuration
VITE_APP_NAME=BetSure Dialer
VITE_APP_ENV=development

# Feature Flags
VITE_ENABLE_WHATSAPP=true
VITE_ENABLE_AI_COACH=true
VITE_ENABLE_CALL_RECORDING=true
EOF

echo "✓ .env updated for Local Supabase"
echo ""
echo "Local services:"
echo "  - API: http://127.0.0.1:54321"
echo "  - Studio: http://127.0.0.1:54323"
echo "  - Database: postgresql://postgres:postgres@127.0.0.1:54322/postgres"
echo ""
echo "Run 'npm run dev' to start the app"

