#!/bin/bash

# Switch to Cloud Supabase (Production)
# This script updates .env to use the cloud Supabase instance

cd "$(dirname "$0")/.."

echo "Switching to Cloud Supabase..."

# Production credentials (from original codebase)
cat > .env << 'EOF'
# BetSure Dialer - CLOUD/Production
# Auto-generated by use-cloud-supabase.sh

# Cloud Supabase
VITE_SUPABASE_URL=https://hahkgifqajdnhvkbzwfx.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhaGtnaWZxYWpkbmh2a2J6d2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTE5MzIsImV4cCI6MjA3NDcyNzkzMn0.iLCXA3OSkvbbQzfSp9ir_beIUlXZQY6g6goN88oighQ

# App Configuration
VITE_APP_NAME=BetSure Dialer
VITE_APP_ENV=production

# Feature Flags
VITE_ENABLE_WHATSAPP=true
VITE_ENABLE_AI_COACH=true
VITE_ENABLE_CALL_RECORDING=true
EOF

echo "✓ .env updated for Cloud Supabase"
echo ""
echo "Using: https://hahkgifqajdnhvkbzwfx.supabase.co"
echo ""
echo "Run 'npm run dev' to start the app"

